# Generated by Django 3.1.5 on 2021-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='recetas/qr'),
        ),
    ]
