# Generated by Django 3.1.5 on 2021-02-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='img/recetas/qr'),
        ),
    ]
