# Generated by Django 3.1.4 on 2021-01-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_auto_20210126_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='fecha',
            new_name='date',
        ),
    ]
