# Generated by Django 3.1.4 on 2021-01-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_auto_20210126_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='date',
            new_name='fecha',
        ),
    ]
