# Generated by Django 3.1.5 on 2021-02-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='universidad',
        ),
        migrations.AddField(
            model_name='doctor',
            name='cedula',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='firma',
            field=models.ImageField(null=True, upload_to='staticfiles/doctor/firmas'),
        ),
    ]
