# Generated by Django 3.1.5 on 2021-02-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210201_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='firma',
            field=models.ImageField(null=True, upload_to='img/doctor/firmas'),
        ),
    ]
