# Generated by Django 3.1.4 on 2021-01-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210119_1530'),
        ('users', '0004_auto_20210115_1704'),
    ]

    operations = [
    ]
