# Generated by Django 3.1.4 on 2021-01-13 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210112_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cp',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.RegexValidator('r^\\d{5}$')]),
        ),
    ]
