# Generated by Django 3.1.4 on 2020-12-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20201215_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_token',
            new_name='room_sid',
        ),
    ]
