# Generated by Django 3.1.4 on 2020-12-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_auto_20201215_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='room',
        ),
    ]
